version: '3.8'

services:
  app:
    build: ./app
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    build: ./db
    ports:
      - "27017:27017"
  seed:
    image: python:3.9-slim
    volumes:
      - ./seed:/seed
    working_dir: /seed
    command: python seed_db.py
    depends_on:
      - db
volumes:
  db-data: