apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-app
  labels:
    app: movie-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-app
  template:
    metadata:
      labels:
        app: movie-app
    spec:
      containers:
        - name: app
          image: app-image:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_HOST
              value: db
        - name: db
          image: mongo:5.0
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: movie-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30080
      name: http # Add a unique name for the HTTP port
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongodb # Add a unique name for the MongoDB port
  selector:
    app: movie-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movie-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: movie-app.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: movie-app
                port:
                  number: 8080
