apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: movie-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:your-repo/movie-app.git
    targetRevision: HEAD
    path: helm-charts
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true