name: Helm Deployment Pipeline

on:
  push:
    branches:
      - main
    paths:
       - .github/workflows/application-deployment.yml
       - movie-app/**

jobs:
  build-and-deploy:
    name: Build, Push, and Deploy with Helm
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Log in to Azure using az login
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 3: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 4: Log in to Azure Container Registry
    - name: Log in to Azure Container Registry
      run: |
        az acr login --name ${{ secrets.ACR_USERNAME }}

    # Step 5: Build and Push Backend Image
    - name: Build and Push Backend Image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/backend:latest movie-app/backend
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/backend:latest

    # Step 6: Build and Push Frontend Image
    - name: Build and Push Frontend Image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest movie-app/frontend
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest
    
    # Step 6: Build and Push Frontend Image
    - name: Build and Push Mongodb image Image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/mongodb:latest movie-app/mongodb
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/mongodb:latest
    
        # Step 6: Build and Push Frontend Image
    - name: Seeding of Data
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/seed:latest movie-app/seed
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/seed:latest


    # Step 7: Configure kubectl for AKS
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.27.1'

    - name: Log in to AKS
      run: |
        az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_AKS_CLUSTER_NAME }}

    # Step 8: Deploy with Helm CLI
    - name: Deploy with Helm CLI
      run: |
          - name: Deploy Backend, Frontend, MongoDB, and Ingress with Helm
            helm upgrade --install backend helm-charts/backend \
              --namespace default \
              --create-namespace \
              --set image.repository=${{ secrets.ACR_LOGIN_SERVER }}/backend \
              --set image.tag=latest

            # Deploy the Frontend Helm chart
            helm upgrade --install frontend helm-charts/frontend \
              --namespace default \
              --set image.repository=${{ secrets.ACR_LOGIN_SERVER }}/frontend \
              --set image.tag=latest

            # Deploy the MongoDB Helm chart (with seed job enabled)
            helm upgrade --install mongodb helm-charts/mongodb \
              --namespace default \
              --set seed.enabled=true \
              --set seed.image.repository=${{ secrets.ACR_LOGIN_SERVER }}/seed \
              --set seed.image.tag=latest

            # Deploy the Ingress Helm chart
            helm upgrade --install ingress helm-charts/ingress \
              --namespace default