name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Images
        run: |
          docker build -t your-docker-repo/app-image:latest ./app
          docker build -t your-docker-repo/db-image:latest ./db
      - name: Push Docker Images
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push your-docker-repo/app-image:latest
          docker push your-docker-repo/db-image:latest