name: infra

on:
  workflow_dispatch:
    inputs:
      tf-extra-args:
        type: string
        default: ""
        description: Extra args for terraform
  push:
    tags: ["v*"]
    branches:
      - main
    

permissions:
  contents: read
  id-token: write

jobs:
  k8s-infra:
    runs-on: ubuntu-latest
    environment: default
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_USE_OIDC: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Log in with Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Terraform
        working-directory: terraform
        run: |
          terraform --version
          terraform init
          terraform plan ${{ inputs.tf-extra-args || '' }} -out plan.infra
          terraform apply -auto-approve plan.infra