name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Azure Login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      # Step 4: Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      # Step 5: Terraform Plan
      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform

      # Step 6: Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform
